# Generated by Django 6.1.1 on 2026-09-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=100)),
                ('code_number', models.PositiveSmallIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Admin Editable'), (2, 'Locked')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CountyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.county')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.foodcode')),
            ],
        ),
        migrations.CreateModel(
            name='CountyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_unit', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.countycategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.item')),
            ],
        ),
        migrations.CreateModel(
            name='CountyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.county')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.county')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=100)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.county')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.week')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('pk', models.CompositePrimaryKey('invoice_id', 'code_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.foodcode')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.manager'),
        ),
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.region'),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.state'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('pk', models.CompositePrimaryKey('county_item_id', 'week_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('end_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('end_received_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('end_received_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('end_inventory', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('deep_dive', models.TextField(blank=True)),
                ('county_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.countyitem')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.week')),
            ],
        ),
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('pk', models.CompositePrimaryKey('county_meal_id', 'week_id', 'sale_date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('sale_count', models.PositiveSmallIntegerField(default=0)),
                ('county_meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.countymeal')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.week')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPayroll',
            fields=[
                ('pk', models.CompositePrimaryKey('employee_id', 'week_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overtime_explanation', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.employee')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.week')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySignoff',
            fields=[
                ('pk', models.CompositePrimaryKey('county_id', 'week_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.county')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.manager')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.week')),
            ],
        ),
        migrations.AddConstraint(
            model_name='countycategory',
            constraint=models.UniqueConstraint(fields=('county', 'code', 'subcategory_id'), name='unique_county_code_subcategory'),
        ),
        migrations.AddConstraint(
            model_name='countyitem',
            constraint=models.UniqueConstraint(fields=('item', 'category'), name='unique_item_category'),
        ),
        migrations.AddConstraint(
            model_name='countymeal',
            constraint=models.UniqueConstraint(fields=('county', 'meal'), name='unique_county_meal'),
        ),
        migrations.AddConstraint(
            model_name='county',
            constraint=models.UniqueConstraint(fields=('county_name', 'state'), name='unique_county_name_per_state'),
        ),
    ]
