# Generated by Django 6.1.1 on 2026-09-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='countycategory',
            options={'verbose_name_plural': 'County categories'},
        ),
        migrations.AlterModelOptions(
            name='countyitem',
            options={'verbose_name_plural': 'County items'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='weeklypayroll',
            options={'verbose_name_plural': 'Weekly payroll'},
        ),
        migrations.AlterField(
            model_name='county',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_system.region'),
        ),
    ]
