# Generated by Django 6.1.1 on 2026-09-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['-is_active', 'county_name', 'state__state_name'], 'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-is_active', 'employee_name']},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['-is_active', 'manager_name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['-is_active', 'region_name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-is_active', 'state_name']},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-end_date', 'county__county_name', 'county__state__state_name']},
        ),
        migrations.AlterModelOptions(
            name='weeklypayroll',
            options={'ordering': ['-week__end_date', 'employee__employee_name', 'employee__county__county_name', 'employee__county__state__state_name'], 'verbose_name_plural': 'Weekly payroll'},
        ),
        migrations.AddField(
            model_name='state',
            name='state_abbreviation',
            field=models.CharField(default='KY', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
