# Generated by Django 6.1.1 on 2026-09-10 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_alter_county_options_alter_countycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_system.region'),
        ),
    ]
