# Generated by Django 6.1.1 on 2026-09-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_alter_county_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['-is_active', 'county_name', 'state__state_abbreviation'], 'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='countycategory',
            options={'ordering': ['-is_active', 'county__county_name', 'code__code_number', 'subcategory_id'], 'verbose_name_plural': 'County categories'},
        ),
        migrations.AlterModelOptions(
            name='countyitem',
            options={'ordering': ['-is_active', 'category__county__county_name', 'category__county__state__state_abbreviation', 'category__code__code_number', 'category__subcategory_id', 'item__item_name'], 'verbose_name_plural': 'County items'},
        ),
        migrations.AlterModelOptions(
            name='countymeal',
            options={'ordering': ['-is_active', 'county__county_name', 'county__state__state_abbreviation', 'meal__meal_name']},
        ),
        migrations.AlterModelOptions(
            name='dailysale',
            options={'ordering': ['-week__end_date', 'county_meal__county__county_name', 'county_meal__county__state__state_abbreviation', 'county_meal__meal__meal_name', '-sale_date']},
        ),
        migrations.AlterModelOptions(
            name='foodcode',
            options={'ordering': ['-is_active', 'code_number']},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-week__end_date', 'county_item__category__county__county_name', 'county_item__category__county__state__state_abbreviation', 'county_item__category__code__code_number', 'county_item__category__subcategory_id', 'county_item__item__item_name'], 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-week__end_date', 'week__county__county_name', 'week__county__state__state_abbreviation', 'vendor_name', 'invoice_number']},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'ordering': ['-invoice__week__end_date', 'invoice__week__county__county_name', 'invoice__week__county__state__state_abbreviation', 'invoice__vendor_name', 'code__code_number']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-is_active', 'item_name']},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-is_active', 'meal_name']},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-end_date', 'county__county_name', 'county__state__state_abbreviation']},
        ),
        migrations.AlterModelOptions(
            name='weeklypayroll',
            options={'ordering': ['-week__end_date', 'employee__employee_name', 'employee__county__county_name', 'employee__county__state__state_abbreviation'], 'verbose_name_plural': 'Weekly payroll'},
        ),
        migrations.AlterModelOptions(
            name='weeklysignoff',
            options={'ordering': ['-week__end_date', '-signed_at', 'week__county__county_name', 'week__county__state__state_abbreviation']},
        ),
    ]
