# Generated by Django 6.1.1 on 2026-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0003_alter_county_options_alter_countycategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='tracking_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
    ]
