# Generated by Django 6.1.1 on 2026-09-16 16:08

from django.db import migrations


def copy_units_forward(apps, schema_editor):
    CountyItem = apps.get_model("inventory_system", "CountyItem")
    Inventory = apps.get_model("inventory_system", "Inventory")
    Unit = apps.get_model("inventory_system", "Unit")

    unit_cache = {}
    for county_item in CountyItem.objects.all():
        unit_name = (county_item.item_unit or "").strip()
        if not unit_name:
            continue
        key = unit_name.lower()
        if key not in unit_cache:
            unit, _ = Unit.objects.get_or_create(unit_name=unit_name, defaults={"is_active": True})
            unit_cache[key] = unit
        Inventory.objects.filter(county_item=county_item).update(unit=unit_cache[key])


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_system", "0006_unit_countyitem_display_name_inventory_unit"),
    ]
    operations = [
        migrations.RunPython(copy_units_forward, migrations.RunPython.noop),
    ]