# Generated by Django 6.1.1 on 2026-09-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0007_move_units_to_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countyitem',
            options={'ordering': ['-is_active', 'category__county__county_name', 'category__county__state__state_abbreviation', 'category__code__code_number', 'category__subcategory_id', 'display_name'], 'verbose_name_plural': 'County items'},
        ),
        migrations.RemoveField(
            model_name='countyitem',
            name='item_unit',
        ),
    ]
