# Generated by Django 6.1.1 on 2026-09-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0009_move_units_back_to_countyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_system.unit'),
        ),
    ]
