# Generated by Django 6.1.1 on 2026-09-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0011_move_units_back_to_countyitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='unit',
        ),
    ]
