# Generated by Django 6.1.1 on 2026-09-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0012_remove_inventory_unit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='countyitem',
            name='unique_item_category',
        ),
        migrations.AddConstraint(
            model_name='countyitem',
            constraint=models.UniqueConstraint(fields=('item', 'category', 'unit'), name='unique_item_category_unit'),
        ),
    ]
