# Generated by Django 6.1.1 on 2026-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0013_remove_countyitem_unique_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
