# Generated by Django 6.1.1 on 2026-09-16 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0015_remove_employee_user_county_login_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='county',
            name='unique_county_name_per_state',
        ),
        migrations.RemoveConstraint(
            model_name='countycategory',
            name='unique_county_code_subcategory',
        ),
        migrations.RemoveConstraint(
            model_name='countyitem',
            name='unique_item_category_unit',
        ),
        migrations.RemoveConstraint(
            model_name='countymeal',
            name='unique_county_meal',
        ),
        migrations.AlterField(
            model_name='county',
            name='login_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_login', to=settings.AUTH_USER_MODEL, verbose_name='Employee user account'),
        ),
        migrations.AddConstraint(
            model_name='county',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('county_name', 'state'), name='unique_county_name_per_state'),
        ),
        migrations.AddConstraint(
            model_name='countycategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('county', 'code', 'subcategory_id'), name='unique_county_code_subcategory'),
        ),
        migrations.AddConstraint(
            model_name='countyitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('item', 'category', 'unit'), name='unique_item_category_unit'),
        ),
        migrations.AddConstraint(
            model_name='countymeal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('county', 'meal'), name='unique_county_meal'),
        ),
    ]
