# Generated by Django 6.1.1 on 2026-09-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0016_remove_county_unique_county_name_per_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
