# Generated by Django 6.1.1 on 2026-09-17 13:26

from django.db import migrations

def set_initial_order(apps, schema_editor):
    CountyItem = apps.get_model("inventory_system", "CountyItem")
    CountyCategory = apps.get_model("inventory_system", "CountyCategory")

    for category in CountyCategory.objects.all():
        items = CountyItem.objects.filter(category=category).order_by("pk")
        for index, item in enumerate(items):
            item.sort_order = index
            item.save()

class Migration(migrations.Migration):
    dependencies = [("inventory_system", "0017_countyitem_sort_order")]
    operations = [migrations.RunPython(set_initial_order, migrations.RunPython.noop)]