# Generated by Django 6.1.1 on 2026-09-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0018_set_initial_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', 'vendor_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-week__end_date', 'week__county__county_name', 'week__county__state__state_abbreviation', 'vendor__vendor_name', 'invoice_number']},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'ordering': ['-invoice__week__end_date', 'invoice__week__county__county_name', 'invoice__week__county__state__state_abbreviation', 'invoice__vendor__vendor_name', 'code__code_number']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory_system.vendor'),
            preserve_default=False,
        ),
    ]
