# Generated by Django 6.1.1 on 2026-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0019_vendor_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_new_item',
            field=models.BooleanField(default=False),
        ),
    ]
