# Generated by Django 6.1.1 on 2026-09-22 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0020_inventory_is_new_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_code', models.CharField(max_length=10, unique=True)),
                ('recipe_code_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['recipe_code'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_size', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('recipe_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.recipecode')),
            ],
            options={
                'ordering': ['recipe_code__recipe_code', 'recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('ingredient_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('ingredient_unit', models.CharField(blank=True, max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory_system.recipe')),
            ],
            options={
                'ordering': ['recipe__recipe_code__recipe_code', 'recipe__recipe_name'],
            },
        ),
        migrations.CreateModel(
            name='CountyRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_number', models.CharField(max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.county')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_system.recipe')),
            ],
            options={
                'ordering': ['county__county_name', 'county__state__state_abbreviation', 'recipe__recipe_code__recipe_code', 'recipe_number'],
                'constraints': [models.UniqueConstraint(fields=('county', 'recipe'), name='unique_county_recipe')],
            },
        ),
    ]
