# Generated by Django 6.1.1 on 2026-09-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0021_recipecode_recipe_recipeingredient_countyrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='countyrecipe',
            name='last_servings',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
