# Generated by Django 6.1.1 on 2026-09-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0022_countyrecipe_last_servings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serving_unit',
            field=models.IntegerField(choices=[(0, 'Portions'), (1, 'Sheetpans')], default=0),
        ),
        migrations.AlterField(
            model_name='countyrecipe',
            name='last_servings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
