# Generated by Django 6.1.1 on 2026-09-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0023_recipe_serving_unit_alter_countyrecipe_last_servings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['recipe__recipe_code__recipe_code', 'recipe__recipe_name', 'sort_order']},
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='is_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
