# Generated by Django 6.1.1 on 2026-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0025_countymeal_used_in_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='countymeal',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
