# Generated by Django 6.1.1 on 2026-10-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0026_countymeal_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countymeal',
            options={'ordering': ['-is_active', 'county__county_name', 'county__state__state_abbreviation', 'order', 'meal__meal_name']},
        ),
        migrations.AddField(
            model_name='inventory',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
