# Generated by Django 6.1.1 on 2026-10-07 19:00

from django.db import migrations
from django.db.models import OuterRef, Subquery


def copy_sort_order_to_inventory(apps, schema_editor):
    Inventory = apps.get_model("inventory_system", "Inventory")
    CountyItem = apps.get_model("inventory_system", "CountyItem")
    # One UPDATE: every existing Inventory row starts with the position its
    # CountyItem currently has, so every week keeps looking exactly as it does now.
    Inventory.objects.update(
        sort_order=Subquery(
            CountyItem.objects.filter(pk=OuterRef("county_item_id")).values("sort_order")[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0027_alter_countymeal_options_inventory_sort_order'),
    ]

    operations = [
        migrations.RunPython(copy_sort_order_to_inventory, migrations.RunPython.noop),
    ]