# Generated by Django 6.1.1 on 2026-10-07 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0028_copy_sort_order_to_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_label', models.CharField(max_length=150)),
                ('page', models.CharField(choices=[('inventory', 'Inventory'), ('daily_sales', 'Daily Sales'), ('invoices', 'Weekly Invoices Recap'), ('payroll', 'WOR Payroll'), ('signoff', 'Sign-off'), ('rollover', 'Rollover')], max_length=20)),
                ('action', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('field_name', models.CharField(blank=True, max_length=60)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_system.county')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory_system.week')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
